title: Titanis Docs
description: Documentation for Titanis, an open-source machine learning library for Apache Spark.
theme: just-the-docs
logo: "./assets/titanis-logo-title.png"
favicon_ico: "/assets/favicon.ico"

aux_links:
  "Titanis on GitHub":
    - "https://github.com/adaptive-machine-learning/titanis"

callouts:
  note:
    title: Note
    color: purple